# ============================================================
# NexusFlow — Airflow Helm Values
# File: kubernetes/airflow/values.yml

# webserver     → scheduler → triggerer → dags →
# logs          → data      → postgresql → redis →
# env           → serviceAccount
# ============================================================

airflowVersion: "2.10.5"
executor: LocalExecutor

webserver:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  startupProbe:
    timeoutSeconds: 30
    failureThreshold: 20
    periodSeconds: 10
  livenessProbe:
    timeoutSeconds: 30
    failureThreshold: 20
    periodSeconds: 10
  readinessProbe:
    timeoutSeconds: 30
    failureThreshold: 20
    periodSeconds: 10
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@nexusflow.io
    firstName: Nexus
    lastName: Flow
    password: nexusflow2026   # DEMO CREDENTIALS ⚠️ change for prod

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

triggerer:
  enabled: false

dags:
  gitSync:
    enabled: true
    repo: https://github.com/smshde/NexusFlow-DataOps-Pipeline.git # ⚠️ 
    branch: main
    subPath: airflow/dags

logs:
  persistence:
    enabled: false

# database connection
data:
  metadataConnection:
    user: airflow
    pass: airflow
    host: airflow-postgres
    port: 5432 
    db: airflow
    sslmode: disable

postgresql:
  enabled: false

redis:
  enabled: false

env:
  - name: AIRFLOW__CORE__LOAD_EXAMPLES
    value: "false"
  - name: NEXUSFLOW_ENV
    value: "dev"
  - name: AWS_REGION
    value: "ca-central-1"
        
serviceAccount:
  create: true
  name: airflow-scheduler
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::167868295416:role/nexusflow-dev-airflow-irsa # ⚠️ 


